name: base
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2020.07=py38_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py38_0
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.3.0=mkl
  - absl-py=0.15.0=pyhd3eb1b0_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=custom=py38_1
  - anaconda-client=1.9.0=py38h06a4308_0
  - anaconda-navigator=2.0.3=py38_0
  - anaconda-project=0.10.2=pyhd3eb1b0_0
  - anyio=2.2.0=py38h06a4308_1
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argh=0.26.2=py38_0
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - asn1crypto=1.4.0=py_0
  - astor=0.8.1=py38h06a4308_0
  - astroid=2.6.6=py38h06a4308_0
  - astropy=4.2.1=py38h27cfd23_1
  - astunparse=1.6.3=py_0
  - async_generator=1.10=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - autopep8=1.5.6=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.0=pyhd3eb1b0_2
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.shutil_get_terminal_size=1.0.0=pyhd3eb1b0_3
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - beautifulsoup4=4.10.0=pyh06a4308_0
  - bitarray=2.3.0=py38h7f8727e_1
  - bkcharts=0.2=py38_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - blinker=1.4=py38h06a4308_0
  - blosc=1.21.0=h8c45485_0
  - bokeh=2.3.2=py38h06a4308_0
  - boto=2.49.0=py38_0
  - bottleneck=1.3.2=py38heb32a55_1
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.10.8=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - cftime=1.5.0=py38h6323ea4_0
  - chardet=4.0.0=py38h06a4308_1003
  - click=7.1.2=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clyent=1.2.2=py38_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=4.11.0=py38h578d9bd_0
  - conda-build=3.21.4=py38h06a4308_0
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-env=2.6.0=1
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=1.7.3=py38h27cfd23_1
  - conda-repo-cli=1.0.4=pyhd3eb1b0_0
  - conda-token=0.3.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - configparser=5.0.2=pyhd3eb1b0_0
  - contextlib2=0.6.0.post1=pyhd3eb1b0_0
  - coverage=5.3=py38h1e0a361_1
  - cryptography=3.4.8=py38hd23ed53_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - curl=7.80.0=h7f8727e_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.25=py38hdbfa776_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask=2021.4.0=pyhd3eb1b0_0
  - dask-core=2021.4.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - distributed=2021.4.1=py38h06a4308_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - docutils=0.17.1=py38h06a4308_1
  - einops=0.3.2=pyhd8ed1ab_0
  - entrypoints=0.3=py38_0
  - et_xmlfile=1.1.0=py38h06a4308_0
  - expat=2.4.1=h2531618_2
  - fastcache=1.1.0=py38h7b6447c_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.4.0=pyhd3eb1b0_0
  - flake8=3.9.0=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - fribidi=1.0.10=h7b6447c_0
  - ftfy=5.8=py_0
  - future=0.18.2=py38_1
  - gast=0.4.0=pyhd3eb1b0_0
  - get_terminal_size=1.0.0=haa9412d_0
  - gevent=21.8.0=py38h7f8727e_1
  - giflib=5.2.1=h7b6447c_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.24=pyhd8ed1ab_0
  - glib=2.69.1=h5202010_0
  - glob2=0.7=pyhd3eb1b0_0
  - gmp=6.2.1=h2531618_2
  - gmpy2=2.0.8=py38hd5f6e3b_3
  - gnutls=3.6.15=he1e5248_0
  - google-auth=1.21.3=py_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=h23475e2_0
  - greenlet=1.1.1=py38h295c915_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - harfbuzz=2.8.1=h6f93f22_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - html5lib=1.1=pyhd3eb1b0_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imagesize=1.3.0=pyhd3eb1b0_0
  - importlib-metadata=4.8.2=py38h06a4308_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.4.1=py38h06a4308_1
  - ipython=7.29.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jbig=2.1=hdba287a_0
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jedi=0.17.2=py38h06a4308_1
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py38_7
  - jupyter-packaging=0.7.12=pyhd3eb1b0_0
  - jupyter_client=7.1.0=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38h06a4308_0
  - jupyter_server=1.4.1=py38h06a4308_0
  - jupyterlab=3.2.1=pyhd3eb1b0_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.8.2=pyhd3eb1b0_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras-base=2.4.3=pyhd3eb1b0_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyring=23.4.0=py38h06a4308_0
  - kiwisolver=1.3.1=py38h2531618_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lazy-object-proxy=1.6.0=py38h27cfd23_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libarchive=3.4.2=h62408e4_0
  - libcurl=7.80.0=h0b77cf5_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - liblief=0.10.1=he6710b0_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm9=9.0.1=h4a3c616_1
  - libnetcdf=4.7.3=hb80b6cc_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libtool=2.4.6=h7b6447c_1005
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - libxslt=1.1.34=hc22bd24_0
  - llvmlite=0.36.0=py38h612dafd_4
  - locket=0.2.1=py38h06a4308_1
  - lxml=4.7.1=py38h1f438cf_1
  - lz4-c=1.9.3=h295c915_1
  - lzo=2.10=h7b6447c_2
  - markdown=3.3.4=py38h06a4308_0
  - markupsafe=2.0.1=py38h27cfd23_0
  - matplotlib=3.3.4=py38h06a4308_0
  - matplotlib-base=3.3.4=py38h62a2d02_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.1=py38ha9443f7_2
  - mock=4.0.3=pyhd3eb1b0_0
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py38h06a4308_0
  - msgpack-python=1.0.2=py38hff7bd54_1
  - multipledispatch=0.6.0=py38_0
  - mypy_extensions=0.4.3=py38h06a4308_1
  - navigator-updater=0.2.1=py38_0
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.3.0=py38h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - netcdf4=1.5.3=py38hbf33ddf_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.3=pyhd3eb1b0_0
  - ninja=1.10.2=py38hd09550d_3
  - nltk=3.6.1=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1006
  - notebook=6.4.6=py38h06a4308_0
  - numba=0.53.1=py38ha9443f7_0
  - numexpr=2.7.3=py38h22e1b3c_1
  - numpy-base=1.20.1=py38h7d8b39e_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=pyhd3eb1b0_0
  - omegaconf=2.1.1=py38h578d9bd_1
  - openh264=2.1.1=h4ff587b_0
  - openpyxl=3.0.9=pyhd3eb1b0_0
  - openssl=1.1.1l=h7f8727e_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.2.4=py38h2531618_0
  - pandoc=2.12=h06a4308_0
  - pandocfilters=1.4.3=py38h06a4308_1
  - pango=1.45.3=hd140c19_0
  - parso=0.7.0=py_0
  - partd=1.2.0=pyhd3eb1b0_0
  - patchelf=0.13=h295c915_0
  - path=16.0.0=py38h06a4308_0
  - path.py=12.5.0=hd3eb1b0_0
  - pathlib2=2.3.6=py38h06a4308_2
  - pathspec=0.7.0=py_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - patsy=0.5.1=py38_0
  - pcre=8.45=h295c915_0
  - pep8=1.7.1=py38_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py38h5aabda8_0
  - pip=21.2.4=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pkginfo=1.7.1=py38h06a4308_0
  - pluggy=1.0.0=py38h06a4308_0
  - ply=3.11=py38_0
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - promise=2.3=py38h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protobuf=3.17.2=py38h295c915_0
  - psutil=5.8.0=py38h27cfd23_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.10.0=pyhd3eb1b0_0
  - py-lief=0.10.1=py38h403a769_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.6.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pycurl=7.44.1=py38h8f2d780_1
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyerfa=1.7.3=py38h27cfd23_0
  - pyflakes=2.2.0=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyjwt=2.1.0=py38h06a4308_0
  - pylint=2.9.6=py38h06a4308_1
  - pyls-black=0.4.6=hd3eb1b0_0
  - pyls-spyder=0.3.2=pyhd3eb1b0_0
  - pyodbc=4.0.32=py38h295c915_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.0=py38heee7806_0
  - pysocks=1.7.1=py38h06a4308_0
  - pytables=3.6.1=py38h9fd0a39_0
  - pytest=6.2.5=py38h06a4308_2
  - python=3.8.8=hdb3f193_5
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - python-jsonrpc-server=0.4.0=py_0
  - python-language-server=0.36.2=pyhd3eb1b0_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=py3.8_cuda10.2_cudnn7.6.5_0
  - pytorch-model-summary=0.1.1=py_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38h7b6447c_2
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0=py38h7f8727e_1
  - pyzmq=22.3.0=py38h295c915_2
  - qdarkstyle=2.8.1=py_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - readline=8.1=h27cfd23_0
  - regex=2021.8.3=py38h7f8727e_0
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - ripgrep=12.1.1=0
  - rope=0.21.1=pyhd3eb1b0_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - rtree=0.9.7=py38h06a4308_1
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - sacremoses=0.0.46=pyhd8ed1ab_0
  - scikit-image=0.18.1=py38ha9443f7_0
  - scikit-learn=0.24.1=py38ha9443f7_0
  - scipy=1.6.2=py38had2a1c9_1
  - seaborn=0.11.1=pyhd3eb1b0_0
  - secretstorage=3.3.1=py38h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - sentry-sdk=1.5.1=pyhd8ed1ab_0
  - setuptools=58.0.4=py38h06a4308_0
  - shortuuid=1.0.8=py38h578d9bd_0
  - simplegeneric=0.8.1=py38_2
  - singledispatch=3.7.0=pyhd3eb1b0_1001
  - sip=4.19.13=py38he6710b0_0
  - six=1.16.0=pyhd3eb1b0_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.1.8=he6710b0_0
  - sniffio=1.2.0=py38h06a4308_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=4.2.0=pyhd3eb1b0_1
  - sphinxcontrib=1.0=py38_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - sphinxcontrib-websupport=1.2.4=py_0
  - spyder=4.2.5=py38h06a4308_0
  - spyder-kernels=1.10.2=py38h06a4308_0
  - sqlalchemy=1.4.27=py38h7f8727e_0
  - sqlite=3.37.0=hc218d9a_0
  - statsmodels=0.12.2=py38h27cfd23_0
  - subprocess32=3.5.4=py_1
  - sympy=1.9=py38h06a4308_0
  - tbb=2020.3=hfd86e86_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow-base=2.4.1=mkl_py38h43e0292_0
  - termcolor=1.1.0=py38h06a4308_1
  - terminado=0.9.4=py38h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tk=8.6.11=h1ccaba5_0
  - tokenizers=0.10.3=py38hb317417_1
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchvision=0.10.0=py38_cu102
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typed-ast=1.4.3=py38h7f8727e_1
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - ujson=4.2.0=py38h295c915_0
  - unicodecsv=0.14.1=py38_0
  - unixodbc=2.3.9=h7b6447c_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - wandb=0.12.9=pyhd8ed1ab_0
  - watchdog=1.0.2=py38h06a4308_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.1=py38_0
  - wrapt=1.12.1=py38h7b6447c_1
  - wurlitzer=3.0.2=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xarray=0.16.1=py_0
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=3.0.2=pyhd3eb1b0_0
  - xlwt=1.3.0=py38_0
  - xmltodict=0.12.0=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - yaspin=2.1.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h2531618_0
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7f8727e_4
  - zope=1.0=py38_1
  - zope.event=4.5.0=py38_0
  - zope.interface=5.4.0=py38h7f8727e_0
  - zstd=1.4.9=haebb681_0
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.8
    - async-timeout==4.0.2
    - charset-normalizer==2.0.9
    - chex==0.1.0
    - clip==1.0
    - datasets==1.17.0
    - dill==0.3.4
    - dm-tree==0.1.6
    - flatbuffers==1.12
    - flax==0.3.4
    - frozenlist==1.2.0
    - fsspec==2021.11.1
    - glide-text2im==0.0.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - huggingface-hub==0.2.1
    - hydra-core==1.1.1
    - imagenetv2-pytorch==0.1
    - importlib-resources==5.4.0
    - jax==0.2.11
    - jaxlib==0.1.71
    - keras==2.6.0
    - keras-nightly==2.5.0.dev2021032900
    - kornia==0.6.2
    - libclang==12.0.0
    - lightly==1.2.2
    - lightly-utils==0.0.2
    - multidict==5.2.0
    - multiprocess==0.70.12.2
    - numpy==1.19.5
    - optax==0.1.0
    - pyarrow==6.0.1
    - pydeprecate==0.3.1
    - pytorch-lightning==1.5.8
    - pytorch-ranger==0.1.1
    - taming-transformers==0.0.1
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorflow==2.5.0
    - tensorflow-estimator==2.5.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - torch-optimizer==0.3.0
    - torchmetrics==0.6.2
    - transformers==4.15.0
    - xxhash==2.0.2
    - yarl==1.7.2
prefix: /u/home/h/hbansal/anaconda3
